version: "3.8"
services:
  node1:
    build: .
    environment:
      - MPI_HOSTS=node1,node2,node3,node4
    networks:
      - distributed-network

  node2:
    build: .
    environment:
      - MPI_HOSTS=node1,node2,node3,node4
    networks:
      - distributed-network

  node3:
    build: .
    environment:
      - MPI_HOSTS=node1,node2,node3,node4
    networks:
      - distributed-network

  node4:
    build: .
    environment:
      - MPI_HOSTS=node1,node2,node3,node4
    networks:
      - distributed-network

networks:
  distributed-network:
    driver: bridge